# **What is Numpy**

**NumPy** (Numerical Python) is a Python library used for working with arrays.

- Provides support for multi-dimensional arrays: **1D, 2D, and 3D**
- Offers tools for:
  - Integrating C/C++ code
  - Performing linear algebra
  - Applying Fourier transforms
  - Other scientific computations
- Acts as the foundation for many Python-based data analysis libraries such as:
  - **Pandas**
  - **Scikit-Learn**
  - **TensorFlow**

### 2. How are Lists different from NumPy? <a id="lists-vs-numpy"></a>

#### 🔸 Key Differences:

- **Lists** are built-in Python data structures.
- **NumPy arrays** are provided by the NumPy library and optimized for numerical computations.

| Feature         | Lists             | NumPy Arrays       |
|----------------|-------------------|--------------------|
| **Speed**       | ❌ Slow            | ✅ Fast             |
| **Data Type**   | Can store mixed types | Homogeneous (same data type) |
| **Functionality** | Basic operations  | Advanced math, broadcasting, etc. |
| **Memory Usage** | High              | Optimized/Low      |
| **Performance**  | Not optimized for large datasets | Efficient for large datasets |


### 3. Why is NumPy Faster? <a id="why-numpy-is-faster"></a>

NumPy is faster than regular Python lists because it uses:

#### 🔹 **Fixed Data Type (e.g., Int32)**
- Each element in a NumPy array has the **same fixed size** and data type (e.g., `int32`).
- This allows NumPy to store and access data in **contiguous blocks of memory**.

#### 🔹 **Binary Representation**
- NumPy directly stores values in binary format:
  ```
  Example: 
  5 → Binary: 00000101
     → NumPy Int32: 00000000 00000000 00000000 00000101
  ```
- In contrast, Python lists store more metadata per item:
  - Size
  - Reference Count
  - Object Type
  - Object Value

#### 🔹 **Result:**
- Less overhead
- Faster computation
- More memory-efficient


### 4. Applications of NumPy <a id="applications-of-numpy"></a>

NumPy is widely used in various domains due to its speed and efficiency. Here are some key applications:

- 🔢 **Mathematics**
  - Acts as a replacement for MATLAB in numerical computations

- 📊 **Plotting**
  - Used with libraries like **Matplotlib** for data visualization

- 🖥️ **Backend Development**
  - Powers libraries and tools such as:
    - **Pandas** (data analysis)
    - **Connect 4** (games/simulations)
    - **Digital Photography** (image processing)

- 🤖 **Machine Learning**
  - Forms the core of many ML workflows, often used with **Scikit-Learn**, **TensorFlow**, etc.


In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)


[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# get dimensions
a.ndim

1

In [6]:
b.ndim

2

In [18]:
# Get shape like no of columns and rows (rows,columns)
a.shape

(3,)

In [12]:
b.shape

(2, 3)

In [13]:
# Get DataType
a.dtype

dtype('int32')

In [14]:
b.dtype

dtype('float64')

In [15]:
# Get Size
a.itemsize

4

In [16]:
# Get total size
a.nbytes

12

In [17]:
# Get number of elements
a.size

3

## Accessing/Changing Specific Elements, Rows, Columns, etc


In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
# Get a specific element [r, c]
a[1, 5]

np.int64(13)

In [21]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [23]:
# Getting a little more slicing [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [26]:
a[1,5] = 20
print(a)
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [27]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [32]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [33]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [35]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [36]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [37]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.56198783, 0.51217375],
       [0.74685791, 0.25977956],
       [0.11964323, 0.31850567],
       [0.21123417, 0.98880261]])

In [38]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 1, -2,  5],
       [ 2,  0,  5],
       [-4,  2,  2]], dtype=int32)

In [39]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [41]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [43]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [44]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [51]:
a + 2

array([3, 4, 5, 6])

In [52]:
a - 2

array([-1,  0,  1,  2])

In [53]:
a * 2

array([2, 4, 6, 8])

In [54]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [55]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [56]:
a ** 2

array([ 1,  4,  9, 16])

In [57]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [58]:
# Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Linear Algebra

In [59]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [60]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

## Statistics

In [63]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
np.min(stats)

np.int64(1)

In [65]:
np.max(stats, axis=1)

array([3, 6])

In [66]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [68]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [69]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Load Data from File

In [72]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [73]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])